import { getPrisma } from "./prisma.js";
import { Prisma } from "@prisma/client";

// Lab 2 Issue 4 — Ticket Creation
// BR-01: the official Ticket Number is generated by the backend and must
// be unique. Format: TKT-<year>-<6-digit sequence, per year>.
export function formatTicketNumber(year: number, sequence: number): string {
  return `TKT-${year}-${String(sequence).padStart(6, "0")}`;
}

async function nextSequenceForYear(year: number): Promise<number> {
  const prisma = getPrisma();
  const startOfYear = new Date(Date.UTC(year, 0, 1));
  const startOfNextYear = new Date(Date.UTC(year + 1, 0, 1));

  const count = await prisma.ticket.count({
    where: { createdAt: { gte: startOfYear, lt: startOfNextYear } },
  });

  return count + 1;
}

// Creates the Ticket row with a generated, unique Ticket Number. Because
// the sequence is computed from a COUNT rather than a DB sequence object,
// two concurrent requests could compute the same number — the @unique
// constraint on ticketNumber catches that, and we retry a few times on
// conflict rather than trusting the count alone (BR-01).
export async function createTicketWithGeneratedNumber(
  data: Omit<Prisma.TicketUncheckedCreateInput, "ticketNumber">,
  maxAttempts = 5
) {
  const prisma = getPrisma();
  const year = new Date().getUTCFullYear();

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const sequence = (await nextSequenceForYear(year)) + attempt;
    const ticketNumber = formatTicketNumber(year, sequence);

    try {
      return await prisma.ticket.create({
        data: { ...data, ticketNumber },
      });
    } catch (err) {
      const isUniqueConflict =
        err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002";
      if (!isUniqueConflict || attempt === maxAttempts - 1) {
        throw err;
      }
      // otherwise: loop and try the next sequence number
    }
  }

  throw new Error("Failed to generate a unique ticket number");
}
